package_name = 'com.google.android.calculator'

id_0_btn = package_name + ':id/digit_0'
id_1_btn = package_name + ':id/digit_1'
id_2_btn = package_name + ':id/digit_2'
id_3_btn = package_name + ':id/digit_3'
id_4_btn = package_name + ':id/digit_4'
id_5_btn = package_name + ':id/digit_5'
id_6_btn = package_name + ':id/digit_6'
id_7_btn = package_name + ':id/digit_7'
id_8_btn = package_name + ':id/digit_8'
id_9_btn = package_name + ':id/digit_9'
id_add_btn = package_name + ':id/op_add'
id_eq_btn = package_name + ':id/eq'
id_result_text  = package_name + ':id/result_final'
